[package]
name = "tbp_eq_masses"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = { version = "0.3.31", default-features = false }
macroquad = { version = "0.4.13", default-features = false }
